### ISSUE TITLE
Synchronize the oss.sonatype.org releases with mvnrepository 

### ISSUE THREAD

**Issue by rodoherty1** [PaddyPowerBetfair/rabbitmq-client#12]
The artefacts which we release to oss.sonatype.org are not visible in mvnrepository.org.

The SBT build files need to be updated with configuration properties that will enable synchronising of releases between oss.sonatype.org and mvnrepository.org.

This will ensure that users of this library can pull the library from either source.

**Comment by fancywriter** [comment]
Looks like it was resolved already? http://mvnrepository.org/artifact/com.paddypowerbetfair/rabbitmq-client

**Comment by rodoherty1** [comment]
You're right!  I forgot to close this once I'd verified it.  Thanks for the reminder, Pavel.
